FROM python:3 as compiler

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/

RUN pyinstaller -F dnfc


FROM scratch as binary
COPY --from=compiler /app/dist/dnfc /