FROM centos:8 as compiler
WORKDIR /pyprepare
RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
RUN yum clean all
RUN yum makecache
RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make wget cmake

RUN curl https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tgz --output Python-3.10.14.tgz
RUN tar xzf Python-3.10.14.tgz
WORKDIR /pyprepare/Python-3.10.14
RUN ./configure --enable-shared
RUN make install -j 8
RUN ln -s /usr/local/lib/libpython3.10.so.1.0 /usr/lib64/libpython3.10.so.1.0
RUN pip3 install --upgrade pip


WORKDIR /app
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt


COPY src /app/
RUN pyinstaller -F dnfc


FROM scratch as binary
COPY --from=compiler /app/dist/dnfc /