
ARG SYSTEM_NAME='centos'
ARG VERSION="8"

FROM python:3 as compiler

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/

RUN pyinstaller -F dnfc
#ENTRYPOINT [ "/app/dist/dnfc" ]


ARG SYSTEM_NAME
ARG VERSION
FROM ${SYSTEM_NAME}:${VERSION} as packager

WORKDIR /root/rpmbuild

RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
RUN dnf clean all
RUN dnf makecache
RUN dnf install -y rpmdevtools 
RUN rpmdev-setuptree 

COPY /SPECS/dnfC.spec /root/rpmbuild/SPECS/dnfC.spec
COPY etc /root/dnfC-1.0/etc
COPY src /root/dnfC-1.0/src
COPY --from=compiler /app/dist/dnfc /root/dnfC-1.0/dist/

WORKDIR /root
RUN tar czvf ~/rpmbuild/SOURCES/dnfC-1.0.tar.gz dnfC-1.0

WORKDIR /root/rpmbuild
RUN rpmbuild -ba ~/rpmbuild/SPECS/dnfC.spec

ENTRYPOINT [ "/root/rpmbuild/RPMS/" ]

FROM scratch as rpm_package
COPY --from=packager /root/rpmbuild/RPMS /RPMS
COPY --from=packager /root/rpmbuild/SRPMS /SRPMS
