#!/usr/bin/python3
import sys
 
#main_module_path = "/usr/share/dnfC/"
#main_module_path = "/home/txz/code/dnfC/src"
#sys.path.append(main_module_path)





def suppress_keyboard_interrupt_message():
    """Prevent unsightly KeyboardInterrupt tracebacks.

    Nothing will be printed to the terminal after an uncaught
    :class:`exceptions.KeyboardInterrupt`.

    """
    old_excepthook = sys.excepthook

    def new_hook(type, value, traceback):
        if type != KeyboardInterrupt:
            old_excepthook(type, value, traceback)
        else:
            pass

    sys.excepthook = new_hook


# do this ASAP to prevent tracebacks after ^C during imports
suppress_keyboard_interrupt_message()


    
import dnfC
dnfC.user_main(sys.argv[1:], exit_code=True)